### ISSUE TITLE
MathJax in Cards

### ISSUE THREAD

**Issue by nigef** [justinmc/jQuery-Open-Carousel#3]
Hi again, sorry to open new issue because I do think this plugin is great but I think I need your help with new issue.

Just noticed that (for some reason that I can't figure out yet) the MathJax equations can't render when placed inside a card.

The MathJax at the bottom displays correctly but when placed inside a card it doesn't register. See http://codepen.io/nigelNSF/pen/fpyDJ

(What is MathJax? http://docs.mathjax.org/en/latest/mathjax.html)

**Comment by nigef** [comment]
I don't mean to sound like I'm picking on this carousel; I actually just am more curious about how these things work and it's not too important if never gets solved. But of course it would be amazing if it did :)

**Comment by justinmc** [comment]
I just took a quick look at this and it seems we should definitely be able to get this to work.  I bet it has to do with the order that open carousel and mathjax load in (mathjax on document load, opencarousel on jquery load).

You can load mathjax manually, see this page in the documentation: http://docs.mathjax.org/en/latest/dynamic.html.  The first thing I would try is loading mathjax like that after opencarousel.

I'll take a closer look tomorrow and let you know what I find.

**Comment by nigef** [comment]
Yes it is the late rendering of mathjax. i will try to take a look also
(though over next few weeks) to investigate handling the load event, or
even if the mathjax image font (vs web font) would hold its place in
the rendering flow..

**Comment by justinmc** [comment]
Fixed it!  It was actually just interfering CSS and not at all a problem with the loading of mathjax.  You can grab the latest version I committed and it should just work (4f040d6b6605de9edaf7dc5fc64c4ee9590c95cc).  Also check out my slightly modified codepen: http://codepen.io/justinmc/pen/KmHbD

The problem was that I was applying style to all children of .ocarousel_window_slides recursively, when I should have just done it one level deep.  This was applying style to the mathjax that made the equation not display.
