### ISSUE TITLE
Vertical Carousel

### ISSUE THREAD

**Issue by Msdoob** [justinmc/jQuery-Open-Carousel#6]
Hi 
First I think this plugin is great.
Is it possible to have a vertical carousel?
Thanx.

**Comment by justinmc** [comment]
Thanks!  Unfortunately right now there is no ready-to-go way to set up a vertical carousel, you'd have to change the javascript a bit.

That said, it shouldn't be too hard to do, and this might make a good configuration parameter to add to the project...  I'll take a look at this as soon as I can and see if it won't be a cool addition.

In the meantime, if you happen to hack it yourself, pull requests are always welcome :)

**Comment by justinmc** [comment]
I just added a vertical config parameter and an example, take a look: https://github.com/justinmc/jQuery-Open-Carousel/tree/master/examples/vertical

To use it, just add the parameter to your main ocarousel class div `data-ocarousel-vertical="true"`.  What that does for you is position all your slides vertically on render, then scroll vertically instead of horizontally.  Should work regardless of what other parameters you use.
